/* Mock data for workspace */

const DOCUMENTS = [
  {
    id: 'r-001',
    title: 'Senior Frontend Engineer',
    titleEm: 'Engineer',
    role: 'Resume · v2.4 · zh-CN',
    lang: 'ZH',
    updated: '4 min ago',
    versions: 23,
    views: 142,
    pinned: true,
    sig: 'L',
    live: true,
  },
  {
    id: 'r-002',
    title: 'Full-Stack · Stripe',
    titleEm: 'Stripe',
    role: 'Tailored · Stripe Inc.',
    lang: 'EN',
    updated: 'yesterday',
    versions: 8,
    views: 31,
    sig: 'S',
  },
  {
    id: 'r-003',
    title: 'Indie Hacker Portfolio',
    titleEm: 'Indie',
    role: 'Long-form · solo projects',
    lang: 'EN',
    updated: '3 days ago',
    versions: 12,
    views: 88,
    sig: 'I',
  },
  {
    id: 'r-004',
    title: '独立开发者 · 中文版',
    titleEm: '独立',
    role: 'Long-form · 个人作品集',
    lang: 'ZH',
    updated: '1 week ago',
    versions: 5,
    views: 19,
    sig: '独',
  },
  {
    id: 'r-005',
    title: 'Staff Engineer · Linear',
    titleEm: 'Linear',
    role: 'Tailored · 上次未投递',
    lang: 'EN',
    updated: '2 weeks ago',
    versions: 3,
    views: 12,
    sig: 'L',
  },
];

const APPLICATIONS = [
  { co: 'Vercel',     mono: 'V', loc: 'Remote · NA',         role: 'Senior Frontend',         dept: 'Web Platform',     resume: 'Senior Frontend v2.4', stage: 'onsite',  stageLabel: 'On-site',  match: 92, when: 'Mar 12',  ago: '2d ago' },
  { co: 'Stripe',     mono: 'S', loc: 'Dublin · Hybrid',     role: 'Full-Stack Engineer',     dept: 'Payments API',     resume: 'Full-Stack · Stripe',  stage: 'screen',  stageLabel: 'Recruiter', match: 84, when: 'Mar 10',  ago: '4d ago' },
  { co: 'Linear',     mono: 'L', loc: 'Remote · Global',     role: 'Staff Engineer',          dept: 'Sync Engine',      resume: 'Staff · Linear',       stage: 'offer',   stageLabel: 'Offer',     match: 96, when: 'Mar 04',  ago: '10d ago' },
  { co: 'Anthropic',  mono: 'A', loc: 'SF · On-site',        role: 'Member of Technical Staff', dept: 'Applied',        resume: 'Senior Frontend v2.4', stage: 'applied', stageLabel: 'Applied',   match: 71, when: 'Mar 02',  ago: '12d ago' },
  { co: 'Figma',      mono: 'F', loc: 'NYC · Hybrid',        role: 'Software Engineer · UI',  dept: 'Editor',           resume: 'Senior Frontend v2.4', stage: 'onsite',  stageLabel: 'On-site',  match: 88, when: 'Feb 28',  ago: '14d ago' },
  { co: 'Notion',     mono: 'N', loc: 'SF · Remote-friendly',role: 'Software Engineer',       dept: 'Databases',        resume: 'Indie Hacker',         stage: 'rejected',stageLabel: 'Closed',    match: 64, when: 'Feb 22',  ago: '20d ago' },
];

const COMMITS = [
  {
    type: 'ai',
    msg: <><span className="tag tag--ai">AI</span><b>refactor</b>(experience): tighten Stripe bullets, quantify impact</>,
    meta: 'Claude · auto-edit · 7 lines changed · accepted by you',
    hash: 'c4f2b1e',
    when: '4m',
  },
  {
    type: 'normal',
    msg: <><span className="tag">edit</span>add side-project · <em className="serif-italic">Wavelet</em></>,
    meta: '@lin · projects.mdx · +14 / −0',
    hash: 'd9012a3',
    when: '1h',
  },
  {
    type: 'branch',
    msg: <><span className="tag tag--branch">branch</span>created <b>stripe-tailor</b> from main</>,
    meta: '@lin · forked Senior Frontend v2.4',
    hash: '0f8d4cc',
    when: '6h',
  },
  {
    type: 'ai',
    msg: <><span className="tag tag--ai">AI</span><b>translate</b>(resume): zh-CN ⇄ en-US sections synced</>,
    meta: 'Claude · tool: translate_section · 4 blocks',
    hash: 'a1bb732',
    when: '1d',
  },
  {
    type: 'normal',
    msg: <><span className="tag">export</span>PDF · A4 · serif · 1 page</>,
    meta: 'downloaded by @lin · 312 KB',
    hash: '7e3aa9f',
    when: '1d',
  },
  {
    type: 'normal',
    msg: <><span className="tag">edit</span>update headline · skill ordering</>,
    meta: '@lin · header.mdx · ±5 lines',
    hash: '2c1f9d8',
    when: '2d',
  },
];
